// AuthActions
export const LOADING_VIEW = {
  SHOW: 'LOADING_VIEW_SHOW',
  HIDE: 'LOADING_VIEW_HIDE',
};

export const POPUP_ERROR = {
  SHOW: 'POPUP_ERROR_SHOW',
  HIDE: 'POPUP_ERROR_HIDE',
};

export const POPUP_SUCCESS = {
  SHOW: 'POPUP_SUCCESS_SHOW',
  HIDE: 'POPUP_SUCCESS_HIDE',
};

export const NAVIGATION_APP = {
  NAVIGATE: 'NAVIGATION_APP_NAVIGATE',
  BACK: 'NAVIGATION_APP_BACK',
  RESET: 'NAVIGATION_APP_RESET',
  REPLACE: 'NAVIGATION_APP_REPLACE',
  POP_CUSTOMS: 'NAVIGATION_APP_POP_CUSTOMS',
};
export const PERMISSION_PUSH = 'PERMISSION_PUSH';

export const SET_FONT_SIZE = 'SET_FONT_SIZE';

export const LOGIN_API = {
  REQUEST: 'LOGIN_API_REQUEST',
  SUCCESS: 'LOGIN_API_SUCCESS',
  FAILURE: 'LOGIN_API_FAILURE',
};

export const REGISTER_API = {
  REQUEST: 'REGISTER_API_REQUEST',
  SUCCESS: 'REGISTER_API_SUCCESS',
  FAILURE: 'REGISTER_API_FAILURE',
};

export const LOGIN_TOKEN_API = {
  REQUEST: 'LOGIN_TOKEN_API_REQUEST',
  SUCCESS: 'LOGIN_TOKEN_API_SUCCESS',
  FAILURE: 'LOGIN_TOKEN_API_FAILURE',
};

export const UPDATE_FCM_TOKEN_API = {
  REQUEST: 'UPDATE_FCM_TOKEN_API_REQUEST',
  SUCCESS: 'UPDATE_FCM_TOKEN_API_SUCCESS',
  FAILURE: 'UPDATE_FCM_TOKEN_API_FAILURE',
};

export const CUSTOMERS_API = {
  REQUEST: 'CUSTOMERS_API_REQUEST',
  SUCCESS: 'CUSTOMERS_API_SUCCESS',
  FAILURE: 'CUSTOMERS_API_FAILURE',
};

//category
export const LIST_CATEGORY_API = {
  REQUEST: 'LIST_CATEGORY_API_REQUEST',
  SUCCESS: 'LIST_CATEGORY_API_SUCCESS',
  FAILURE: 'LIST_CATEGORY_API_FAILURE',
};

//service
export const HISTORY_SERVICE_API = {
  REQUEST: 'HISTORY_SERVICE_API_REQUEST',
  SUCCESS: 'HISTORY_SERVICE_API_SUCCESS',
  FAILURE: 'HISTORY_SERVICE_API_FAILURE',
};

export const ORDERS_ID_API = {
  REQUEST: 'ORDERS_ID_API_REQUEST',
  SUCCESS: 'ORDERS_ID_API_SUCCESS',
  FAILURE: 'ORDERS_ID_API_FAILURE',
};

export const ORDERS_DETAIL_ID_API = {
  REQUEST: 'ORDERS_DETAIL_ID_API_REQUEST',
  SUCCESS: 'ORDERS_DETAIL_ID_API_SUCCESS',
  FAILURE: 'ORDERS_DETAIL_ID_API_FAILURE',
};

export const REG_ORDER_API = {
  REQUEST: 'REG_ORDER_API_REQUEST',
  SUCCESS: 'REG_ORDER_API_SUCCESS',
  FAILURE: 'REG_ORDER_API_FAILURE',
};

export const LIST_FAVARITE_STAFF_API = {
  REQUEST: 'LIST_FAVARITE_STAFF_API_REQUEST',
  SUCCESS: 'LIST_FAVARITE_STAFF_API_SUCCESS',
  FAILURE: 'LIST_FAVARITE_STAFF_API_FAILURE',
};

export const ADD_FAVARITE_STAFF_API = {
  REQUEST: 'ADD_FAVARITE_STAFF_API_REQUEST',
  SUCCESS: 'ADD_FAVARITE_STAFF_API_SUCCESS',
  FAILURE: 'ADD_FAVARITE_STAFF_API_FAILURE',
};

export const REMOVE_FAVARITE_STAFF_API = {
  REQUEST: 'REMOVE_FAVARITE_STAFF_API_REQUEST',
  SUCCESS: 'REMOVE_FAVARITE_STAFF_API_SUCCESS',
  FAILURE: 'REMOVE_FAVARITE_STAFF_API_FAILURE',
};

export const EVALUATION_STAFF_API = {
  REQUEST: 'EVALUATION_STAFF_API_REQUEST',
  SUCCESS: 'EVALUATION_STAFF_API_SUCCESS',
  FAILURE: 'EVALUATION_STAFF_API_FAILURE',
};

//public
export const LIST_NOTIFICATIONS_API = {
  REQUEST: 'LIST_NOTIFICATIONS_API_REQUEST',
  SUCCESS: 'LIST_NOTIFICATIONS_API_SUCCESS',
  FAILURE: 'LIST_NOTIFICATIONS_API_FAILURE',
};

export const READ_NOTIFICATIONS_API = {
  REQUEST: 'READ_NOTIFICATIONS_API_REQUEST',
  SUCCESS: 'READ_NOTIFICATIONS_API_SUCCESS',
  FAILURE: 'READ_NOTIFICATIONS_API_FAILURE',
};
